### ISSUE TITLE
Text space added in "Prefix test field" every time I refresh the editor page

### ISSUE THREAD

**Issue by overclokk** [EssentialBlocks/typing-text#1]
Hi, this happen with default config, only added some text in "Prefix test field", every time I refresh the editor page some space is added to that field after the word.

**Comment by tasnimAlam** [comment]
Hello @overclokk ,  we'll release a bug fix soon.

**Comment by tasnimAlam** [comment]
@overclokk , 
We've fixed the issue with our new update today. Please update your plugin to the latest version.

**Comment by overclokk** [comment]
@tasnimAlam Ok, updated, I see there is no space at all and this is a BC for all user that have installed the plugin by removing the default space between prefix-text-suffix, a default space should not be removed between text, instead you have to provide an option to remove the default space as needed, this is for better UX.
