### ISSUE TITLE
Don't enqueue "wp-editor" on front-end

### ISSUE THREAD

**Issue by overclokk** [EssentialBlocks/typing-text#2]
When you enqueue `typed.min.js` and `frontend.js` on `init` hook with "wp-editor" as dependency they will be loaded both on front-end and back-end but "wp-editor" is only needed on back-end, what  you can do is to use the `register_block_type` arguments to load only what you need when you need it, here the arguments reference https://developer.wordpress.org/reference/functions/register_block_type/#comment-3714

Here an example:
```php
[
        'editor_script'   => 'create-block-typing-text-block-editor', // Also import here the type.min.js and frontend inside this file
        'editor_style'    => 'create-block-typing-text-block', // Load the css if you need it.
        'script'          => 'essential-blocks-typing-text-frontend', // Put type.min and frontend in one single file minified.
        'style'           => 'create-block-typing-text-block', // Minify this
]
```

`Type.min` does not require `jQuery` as dependency and maybe you could use vanilla js to do the implementation of it and remove that dependency.

**Comment by Rahat89** [comment]
Thanks for noticing, the issue is resolved
